In [143]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [144]:
#load the model
model = load_model('model.h5')

#load the scaler and encoder
with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)
with open('OHE.pkl', 'rb') as f:
    onehot_encoder = pickle.load(f)
with open('label.pkl', 'rb') as f:
    label_encoder = pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [145]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [146]:
#one hot encode the Geography column
ip_geo=onehot_encoder.transform([[input_data['Geography']]]).toarray()
ip_geo_df=pd.DataFrame(ip_geo,columns=onehot_encoder.get_feature_names_out(['Geography']))

c:\Users\abhip\OneDrive\Documents\MLassignments\MLassignments\Deep Learning\ANN classification\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [147]:
##dataframe for input data
df_input=pd.DataFrame([input_data])
df_input

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [148]:
#label encode for the gender column
df_input['Gender']=label_encoder.transform(df_input['Gender'])

In [149]:
print(label_encoder.classes_)

['Female' 'Male']

In [150]:
print(type(onehot_encoder))
print(type(label_encoder))
print(type(scaler))

<class 'sklearn.preprocessing._encoders.OneHotEncoder'>
<class 'sklearn.preprocessing._label.LabelEncoder'>
<class 'sklearn.preprocessing._data.StandardScaler'>

In [151]:
ip_geo_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [152]:
#concating one hot encoder cols(df_geo) and df
df=pd.concat([df_input.drop('Geography',axis=1),ip_geo_df],axis=1)

In [153]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [155]:
#scale the data
scaled_data=scaler.transform(df)
scaled_data

array([[-0.51822018,  0.91601335,  0.09982384, -0.68638819, -0.26502679,
         0.80997456,  0.64784127,  0.9687384 , -0.86824391,  1.0010005 ,
        -0.5744635 , -0.58100686]])

In [156]:
##predicting churn
pred=model.predict(scaled_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step

In [157]:
pred

array([[0.03863784]], dtype=float32)

In [159]:
if pred>0.5:
    print('the person is not likey to leave')
else:
    print('the person is likey leave')

the person is likey leave